### ISSUE TITLE
Автоматические permission при создании моделей

### ISSUE THREAD

**Issue by GTFB** [GTFB/Altrp3#137]
Добавление в БД следующих permission:

разрешение на создание - {model_name}_create
на чтение - {model_name}_read
на удаление - {model_name}_delete
на обновление - {model_name}_update
на все действия - {model_name}_all

**Comment by 523talp** [comment]
Добавляются в формате {model_name}-read
![image](https://user-images.githubusercontent.com/34745185/86724374-c80a2b80-c039-11ea-88d8-6d35ffad1d4d.png)
