### ISSUE TITLE
Data Sources

### ISSUE THREAD

**Issue by GTFB** [GTFB/Altrp3#219]
- [ ] Data Sources прикрутить к АПИ
![изображение](https://user-images.githubusercontent.com/23271651/91047097-39ba2b00-e622-11ea-8dcb-d6c49b19346b.png)

**Comment by 523talp** [comment]
- [ ] Актуализировать информацию по необходимым полям. 
- [ ] Добавить раздел с Авторизацией из SQLEditor
![image](https://user-images.githubusercontent.com/34745185/93079182-ca71ad00-f69c-11ea-9814-2a9a3cf1c2a4.png)
- [ ] Сверстать формы редактирования и добавления datasource.

Поля type, model_id, url, api_url, name, title, request_type
