### ISSUE TITLE
Php-модуль сохранения/загрузки глобальных элементов

### ISSUE THREAD

**Issue by GTFB** [GTFB/Altrp3#27]

**Comment by 523talp** [comment]
Сохранение и загрузку глобальных шаблонов и элементов реализует контроллер обеспечивающий обработку AJAX-запросов из редактора шаблонов. Этот контроллер должен выполнять:


1. Проверку того что запрос выполнен пользователем с ролью «администратор». Все действия с шаблоном может производить только администратор
2. Сохранение данных элемента в БД для возможности использовать эти элементы повторно
3. CRUD-действия с этими элементами (Модель элементов должна поддерживать возможность “softdeletes” https://laravel.com/docs/6.x/eloquent#soft-deleting)

Описание роутов и данных для запросов к модулю:

/admin/ajax/global-elements - Получение всех GET
/admin/ajax/global-elements/{id} - Получение по ID GET
/admin/ajax/global-elements/{id} - Изменение по ID PUT
/admin/ajax/global-elements/{id} - Удаление по ID DELETE
/admin/ajax/global-elements - Добавление POST
