### ISSUE TITLE
 контекстное меню элементов (колонка, секция, виджет)

### ISSUE THREAD

**Issue by GTFB** [GTFB/Altrp3#49]
- [x] создать/интегрировать компонент меню

- [x] создать контекстное меню

**Comment by GTFB** [comment]
### пункты контекстного меню

- [ ] копировать
- [x] дублировать

- [ ] вставить
- [ ] вставить стили

- [ ] навигатор
- [ ] сбросить стили

- [ ] сохранить как глобальный
- [ ] удалить

**Comment by GTFB** [comment]
можно использовать
https://github.com/vkbansal/react-contextmenu

**Comment by chuikoffru** [comment]
Контекстное меню интегрировал - https://github.com/fkhadra/react-contexify
Навесил события на section, но возникла одна проблема. И этот компонент и react-contextmenu позицию меню слева отсчитывают в рамках iframe, а не в рамках всего окна. В итоге при клике на секцию, контекстное меню отображается на 290px левее от курсора, ровно на ширину левой панели. Придется вносить изменения в чужой компонент.
![Screenshot 2020-06-12 at 15 50 53](https://user-images.githubusercontent.com/8284619/84465525-586b7f80-accb-11ea-89d2-8cbc140099e3.png)

**Comment by chuikoffru** [comment]
В общем, по контекстному меню. 

Поборол проблему с позицией курсора костылями. Позиция верная. Отказался. Решил другой плагин поставить. Встал без проблем, но и у прежнего и у этого виджета одна проблема - меню показывается, но при скролле или при клике в свободное пространство меню не исчезает. 

Хотя событие на window стоит верно. Потратил несколько часов чтобы отловить это событие, ничего не вышло. Меню пропадало только при клике на левую колонку.

Попробовал решить проблему хуками, поставил https://github.com/cluk3/use-context-menu, все здорово красиво, пришлось переписать несколько компонентов, но опять не исчезает при клике на свободное пространство. Что-то мне подсказывает, что с iframe нужно быть осторожнее.
