### ISSUE TITLE
Create request designer. (Customizer)

### ISSUE THREAD

**Issue by alex617180** [GTFB/Altrp3#566]
### List of nodes for processing requests:

- [x] Entrance
- [x] Condition
- [x] Data manipulation
- [x] Server response

**Comment by talp-525** [comment]
### Node settings
### Entrance:

1. Name. Text field
2. Model. Select
3. Request URL. Text field. Example: /test/{id}/{slug}
4. Type of request. Choice of 4 options: GET, POST, PUT, DELETE

**Comment by talp-525** [comment]
### Model Description
altrp_custom_methods

- id 
- name - string
- title - string
- data - long text
- model_id
- type
