### ISSUE TITLE
wysiwyg контроллер

### ISSUE THREAD

**Issue by GTFB** [GTFB/Altrp3#70]
вот здесь контроллеры
![изображение](https://user-images.githubusercontent.com/23271651/83797190-e8497200-a6aa-11ea-858a-ba835c49eaef.png)
подключение wysiwyg редактора асинхронное 
брать библиотеку с минимум 1к звезд

**Comment by chuikoffru** [comment]
Выбирал между react-draft-wysiwyg (4.2k) и react-quill (3.5k).
Остановился на втором, так как первый требует больше зависимостей, и даже не пытается сам поставить их из коробки. Были и еще причины. Но второй вариант завелся без проблем.

**Comment by GTFB** [comment]
исправить отображение
![изображение](https://user-images.githubusercontent.com/23271651/84184449-0988d480-aa96-11ea-906e-7329650144fb.png)

**Comment by chuikoffru** [comment]
Всё! I did it! Пришлось помучиться, поставил другой редактор, думал из-за него проблемы с редактированием, но оказалось проблема в другом, переписал с помощью хуков и функционального компонента, все заработало как швейцарские часы. Тестите! Я закрываюсь. 

P.S Ах да, пока навестил редактор на Text виджет
